### PR TITLE
First notebook

### PR DESCRIPTION
**Pull request by jhamman**
towards #4 

I have a notebook that makes the beginnings of figures 2 and 4.

Figure 2:

lens_fig2

Figure 4 (limited to 20 members for plotting speed):

lens_fig4

What I'd like to do is merge this now and let others (@sethmcg, @andersy005, etc) work here for a bit. The basic pieces are in place and I've noted `#TODO` items throughout.

### CODE REVIEW

**Comment by andersy005** [comment]
@jhamman, thank you for putting this together

> TODO: update zarr version in icesat2 jhub

I noticed that the majority of packages on icesat2 jhub are very outdated. Could we update the entire environment? What is the process for doing this ( I still don't understand the pangeo-cloud-federation magic yet :) ) ?

**Comment by jhamman** [comment]
@andersy005 - We can change the environment through PR's like this one: https://github.com/pangeo-data/pangeo-cloud-federation/pull/394.

**Comment by andersy005** [comment]
> What I'd like to do is merge this now and let others (@sethmcg, @andersy005, etc) work here for a bit. The basic pieces are in place and I've noted #TODO items throughout.

@jhamman, I am merging this for now as you pointed out in a comment above. I've been working on some of the TODO items you listed, and I will submit a PR tomorrow. 


Also, I migrated to https://esip.pangeo.io, and everything seems to be working just fine over there (the environment has more recent package releases).

**Comment by sethmcg** [comment]
Do we have a good sense of who the target audience is for this notebook?  I think it may need more commentary about what various bits of code do, but I don't know what we want to assume about what the reader already knows.

**Pull request merged**
