### PR TITLE
Use intake-esm

### PR DESCRIPTION
**Pull request by andersy005**
Towards #16

### CODE REVIEW

**Comment by bonnland** [comment]
@andersy005 Jeff was hoping to see changes in the other notebook also.   I can make those changes if you want, but I will wait until you indicate that you have the original notebook in a good state.    Or you can make the changes if you like.   Let me know if you have questions.

**Comment by andersy005** [comment]
> Jeff was hoping to see changes in the other notebook also. 

I ended up making changes in the `kay-et-al-2015.v3.ipynb` notebook only. Feel free to update the `kay-et-al-2015.ipynb` notebook in a later PR.

**Comment by andersy005** [comment]
@bonnland, 

When you get time, can you take a look at this? I think that this is ready to be merged.

**Comment by andersy005** [comment]
Live version of my master branch: https://aws-uswest2-binder.pangeo.io/v2/gh/andersy005/cesm-lens-aws/master

**Comment by bonnland** [comment]
Closes #16

**Pull request merged**
